name: Playwright Tests

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]

jobs:

  smoke-tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Smoke Tests (Sharded)
        run: npx playwright test --grep @smoke --browser=${{ matrix.browser }} --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-report-${{ matrix.shardIndex }}
          path: playwright-report

      - name: Upload Screenshots & Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts-${{ matrix.shardIndex }}
          path: test-results


  regression-tests:
    if: github.ref == 'refs/heads/main'
    needs: smoke-tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Full Regression (Sharded)
        run: npx playwright test --browser=${{ matrix.browser }}--shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-report-${{ matrix.shardIndex }}
          path: playwright-report

      - name: Upload Screenshots & Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-artifacts-${{ matrix.shardIndex }}
          path: test-results